[build]
  publish = "dist"
  command = "vite build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

# SPA fallback - redirect all other routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200